name: release
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  call_test:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
  release:
    needs: call_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack and Publish
      env:
        READ_REPO_PACKAGES: ${{ secrets.READ_REPO_PACKAGES }}
      run: |
        cd ./source
        vversion=${{ github.ref_name }}
        dotnet nuget add source "https://nuget.pkg.github.com/ne1410s/index.json" --name ne1410s --username ne1410s --password "${{ env.READ_REPO_PACKAGES }}" --store-password-in-clear-text
        dotnet pack -c Release -o ${{ runner.temp }}/nu -p:Version=${vversion:1}
        echo "skipping push to github feed ..."
        #dotnet nuget push ${{ runner.temp }}/nu/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/ne1410s/index.json"
    - name: Increment patch (if stable release)
      run: |
        if [[ ${{ github.ref_name }} =~ ^v([0-9]+\.[0-9]+\.)([0-9]+)$ ]]
        then
          echo "${{ github.ref_name }} is a stable release version. Incrementing patch."
          vnext="${BASH_REMATCH[1]}$((${BASH_REMATCH[2]} + 1))"
          shopt -s extglob
          for file in "./source/**/!(*.Test*(s)|*.UnitTest*(s)).csproj"; do
            sed "s#<VersionPrefix>[^<]*</VersionPrefix>#<VersionPrefix>$vnext</VersionPrefix>#" $file -i
          done
          git config --global user.email "octocat@github.com"
          git config --global user.name "ci-bot"
          git commit -am "Published ${BASH_REMATCH[0]}: Increment patch [skip ci]."
          git push
        else
          echo "Skipping patch increment. ${{ github.ref_name }} is not a stable release version."
        fi
